#!/bin/bash
# A Shell Blocker
# Block annoying ADs with a simple script.
# Copyright 2015, Federico Damián Schonborn <federicodamians@gmail.com>
# License: GPLv2

# Configurations:

# Set the webpage for downloading the /etc/hosts file:
file_source="http://winhelp2002.mvps.org/hosts.txt"

# Color prompts:
bold="\e[1;34m> \e[0m\e[1m"
error="\e[1;31m\u274C \e[0m\e[1m"
done="\e[32;1m\u2713 \e[0m\e[1m"
endc="\e[0m"

# Functions:

# Print some messages:
print_message() {
  echo -e ""$bold""$1""$endc""
}

# Print some errors:
print_error() {
  echo -e ""$error""$1""$endc""
  exit 1
}

# Print some success:
print_success() {
  echo -e ""$done""$1""$endc""
}

# Check if you're root:
check_root() {
  if [ $(whoami) != "root" ]; then
    print_error "Please run "$0" as ROOT!"
  fi
}

# Check if command runned successfully:
check_success() {
  if [ "$?" == "0" ]; then
    print_success "DONE! :D"
  else
    print_error "FAILED! :("
  fi
}

case $1 in
  about)
    print_message "A Shell Blocker"
    print_message "Block annoying ADs with a simple script."
    print_message "Version: 1.0.1 \"Antares\""
    print_message "License: GPLv2"
    ;;
  update)
    check_root
    print_message "Downloading hosts file..."
    wget ${file_source} -O /etc/hosts
    check_success
    ;;
  help|""|*)
    print_message "Usage: ashblock [COMMAND]"
    print_message "Available commands:"
    print_message "update: Updates the /etc/hosts file"
    print_message "about: About ashblock"
    print_message "help: This."
    ;;
esac
