#!/bin/bash
# A Shell Blocker
# The script for blocking ads on the web.
# Copyright 2015, Federico Damián Schonborn <federicodamians@gmail.com>
# License: GPLv2

# Configurations:

# Set the webpage for downloading the /etc/hosts file:
file_source="http://winhelp2002.mvps.org/hosts.txt"

# Color prompts

bold="\e[1m"
endc="\e[0m"

case $1 in
  about)
    echo -e "\n"$bold"A Shell Blocker"
    echo -e "The script for blocking ads on the web."
    echo -e "License: GPLv2"$endc"\n"
    ;;
  help)
    echo -e "\n"$bold"Usage: ashblock [COMMAND]"$endc"\n"
    echo -e "Available commands:\n"
    echo -e "update   Updates the /etc/hosts file"
    echo -e "about    About ashblock"
    echo -e "help     This.\n"
    ;;
  update)
    if [ $(whoami) != "root" ]; then
      echo -e "\n"$bold"Please run ashblock as ROOT!"$endc"\n"
      exit 1
    fi
    echo -e "\n"$bold"Downloading hosts file..."$endc"\n"
    wget ${file_source} -O /etc/hosts
    if [ "$?" == "0" ]; then
      echo -e "\n"$bold"DONE! :D"$endc"\n"
    else
      echo -e "\n"$bold"FAILED! :("$endc"\n"
    fi
esac
