#!/bin/bash
#
# A Shell Blocker/APyBlock/APyBlock Installer
#
# Copyright (C) 2016 Federico Damián Schonborn <federicodamians@gmail.com>
#
# This file is part of A Shell Blocker/APyBlock.
#
# A Shell Blocker/APyBlock is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# A Shell Blocker/APyBlock is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with A Shell Blocker/APyBlock. If not, see <http://www.gnu.org/licenses/>.

if [ ! $(whoami) = "root" ]; then
  echo -e "ERROR: You need to run this script as root"
  exit 1
fi
echo -en "> A Shell Blocker will be installed, continue? (y/n) "; read installyn
if [[ $installyn == [nN] ]]; then
  echo -e "ERROR: Aborted by user!"
  exit 1
fi
echo -e "> Installing..."
cp -v ashblock /usr/bin/ashblock
echo -en "> Install Cron job? It will update the hosts file every day (y/n) "; read cronyn
if [[ $cronyn == [yY] ]]; then
    if [[ ! -d /etc/cron.daily ]]; then
	mkdir -pv /etc/cron.daily
    fi
    cp -v extra/cronjob/ashblock.cron /etc/cron.daily/ashblock.cron
    echo -e "> Cron job is installed."
fi
echo -en "> Install APyBlock? (y/n) "; read apyblockyn
if [[ $apyblock == [yY] ]]; then
  cp -v apyblock /usr/bin/apyblock
  cp -v extra/cronjob/apyblock.cron
  echo -e "> APyBlock is installed."
fi
echo -e "> Finished!"
